/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILED = "FORGET_PASSWORD_FAILED";

/* STRINGS */

export const ADD_STRING = "ADD_STRING";
export const ADD_STRING_SUCCESS = "ADD_STRING_SUCCESS";
export const ADD_STRING_FAILED = "ADD_STRING_FAILED";
export const UPDATE_STRING = "UPDATE_STRING";
export const UPDATE_STRING_SUCCESS = "UPDATE_STRING_SUCCESS";
export const UPDATE_STRING_FAILED = "UPDATE_STRING_FAILED";
export const DELETE_STRING = "DELETE_STRING";
export const DELETE_STRING_SUCCESS = "DELETE_STRING_SUCCESS";
export const DELETE_STRING_FAILED = "DELETE_STRING_FAILED";

/* PAGE_TITLE */

export const CHANGE_TITLE = "CHANGE_TITLE";
